routes/admin.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');


Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');

//Menu #TODO need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::post('updateChannelPosition', 'MenuController@update_channel_position')->name('channels');

Route::resource('settings', 'SettingController');

Route::resource('order-details', 'OrderDetailController');

//added this
Route::post('/universities/toggleBtn', 'UniversityController@toggleBtn');

Route::post('/customers/toggleBtn', 'CustomerController@toggleBtn');

Route::post('/jobs/toggleBtn', 'JobController@toggleBtn');

Route::post('/transactions/toggleBtn', 'TransactionController@toggleBtn');

Route::post('/refund-customers/refund', 'RefundCustomerController@refund');

Route::post('/refund-customers/toggleBtn', 'RefundCustomerController@toggleBtn');

Route::resource('customers', 'CustomerController');

Route::resource('washers', 'WasherController');

Route::resource('universities', 'UniversityController');

Route::resource('transactions', 'TransactionController');

Route::resource('orders', 'OrderController');

Route::resource('transactions', 'TransactionController');

Route::resource('universities', 'UniversityController');

Route::resource('reports', 'ReportController');

Route::resource('jobs', 'JobController');

Route::resource('total-scholarships', 'TotalScholarshipController');

Route::resource('refund-customers', 'RefundCustomerController');

Route::resource('cancelled-orders', 'CancelledOrderController');

Route::resource('cancelled-orders', 'CancelledOrderController');

Route::resource('cancelled-orders', 'CancelledOrderController');

Route::resource('wallets', 'WalletController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/OrderDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer id
 * @property string name
 * @property string created_at
 * @property string updated_at
 * @property string deleted_at
 *
 * @SWG\Definition(
 *      definition="OrderDetail",
 *      required={"order_id", "no_bags", "type", "detergent", "folded", "hung", "instruction", "price", "donation"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="order_id",
 *          description="order_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="no_bags",
 *          description="no_bags",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="type",
 *          description="type",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="detergent",
 *          description="detergent",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="folded",
 *          description="folded",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="hung",
 *          description="hung",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="instruction",
 *          description="instruction",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="price",
 *          description="price",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="donation",
 *          description="donation",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class OrderDetail extends Model
{
    use SoftDeletes;

    public $table = 'order_details';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'order_id',
        'no_bags',
        'type',
        'detergent',
        'folded',
        'hung',
        'instruction',
        'price',
        'donation'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id'          => 'integer',
        'order_id'    => 'integer',
        'no_bags'     => 'integer',
        'type'        => 'boolean',
        'detergent'   => 'boolean',
        'folded'      => 'boolean',
        'hung'        => 'boolean',
        'instruction' => 'string',
        'price'       => 'string',
        'donation'    => 'string'
    ];

    /**
     * The objects that should be append to toArray.
     *
     * @var array
     */
    protected $with = [];

    /**
     * The attributes that should be append to toArray.
     *
     * @var array
     */
    protected $appends = [];

    /**
     * The attributes that should be visible in toArray.
     *
     * @var array
     */
    protected $visible = [];

    /**
     * Validation create rules
     *
     * @var array
     */
    public static $rules = [
        'order_id'    => 'required',
        'no_bags'     => 'required',
        'type'        => 'required',
        'detergent'   => 'required',
        'folded'      => 'required',
        'hung'        => 'required',
        'instruction' => 'required',
        'price'       => 'required',
        'donation'    => 'required'
    ];

    /**
     * Validation update rules
     *
     * @var array
     */
    public static $update_rules = [
        'order_id'    => 'required',
        'no_bags'     => 'required',
        'type'        => 'required',
        'detergent'   => 'required',
        'folded'      => 'required',
        'hung'        => 'required',
        'instruction' => 'required',
        'price'       => 'required',
        'donation'    => 'required'
    ];

    /**
     * Validation api rules
     *
     * @var array
     */
    public static $api_rules = [
        'order_id'    => 'required',
        'no_bags'     => 'required',
        'type'        => 'required',
        'detergent'   => 'required',
        'folded'      => 'required',
        'hung'        => 'required',
        'instruction' => 'required',
        'price'       => 'required',
        'donation'    => 'required'
    ];

    /**
     * Validation api update rules
     *
     * @var array
     */
    public static $api_update_rules = [
        'order_id'    => 'required',
        'no_bags'     => 'required',
        'type'        => 'required',
        'detergent'   => 'required',
        'folded'      => 'required',
        'hung'        => 'required',
        'instruction' => 'required',
        'price'       => 'required',
        'donation'    => 'required'
    ];

    public function order()
    {
        return $this->belongsTo(Order::class);
    }

}

app/Http/Controllers/Admin/OrderDetailController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\BreadcrumbsRegister;
use App\DataTables\Admin\OrderDetailDataTable;
use App\Http\Requests\Admin;
use App\Http\Requests\Admin\CreateOrderDetailRequest;
use App\Http\Requests\Admin\UpdateOrderDetailRequest;
use App\Repositories\Admin\OrderDetailRepository;
use App\Http\Controllers\AppBaseController;
use Laracasts\Flash\Flash;
use Illuminate\Http\Response;

class OrderDetailController extends AppBaseController
{
    /** ModelName */
    private $ModelName;

    /** BreadCrumbName */
    private $BreadCrumbName;

    /** @var  OrderDetailRepository */
    private $orderDetailRepository;

    public function __construct(OrderDetailRepository $orderDetailRepo)
    {
        $this->orderDetailRepository = $orderDetailRepo;
        $this->ModelName = 'order-details';
        $this->BreadCrumbName = 'Order Details';
    }

    /**
     * Display a listing of the OrderDetail.
     *
     * @param OrderDetailDataTable $orderDetailDataTable
     * @return Response
     */
    public function index(OrderDetailDataTable $orderDetailDataTable)
    {
        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName);
        return $orderDetailDataTable->render('admin.order_details.index', ['title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for creating a new OrderDetail.
     *
     * @return Response
     */
    public function create()
    {
        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName);
        return view('admin.order_details.create')->with(['title' => $this->BreadCrumbName]);
    }

    /**
     * Store a newly created OrderDetail in storage.
     *
     * @param CreateOrderDetailRequest $request
     *
     * @return Response
     */
    public function store(CreateOrderDetailRequest $request)
    {
        $orderDetail = $this->orderDetailRepository->saveRecord($request);

        Flash::success($this->BreadCrumbName . ' saved successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.order-details.create'));
        } elseif (isset($request->translation)) {
            $redirect_to = redirect(route('admin.order-details.edit', $orderDetail->id));
        } else {
            $redirect_to = redirect(route('admin.order-details.index'));
        }
        return $redirect_to->with([
            'title' => $this->BreadCrumbName
        ]);
    }

    /**
     * Display the specified OrderDetail.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $orderDetail = $this->orderDetailRepository->findWithoutFail($id);

        if (empty($orderDetail)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.order-details.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName, $orderDetail);
        return view('admin.order_details.show')->with(['orderDetail' => $orderDetail, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for editing the specified OrderDetail.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $orderDetail = $this->orderDetailRepository->findWithoutFail($id);

        if (empty($orderDetail)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.order-details.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName, $orderDetail);
        return view('admin.order_details.edit')->with(['orderDetail' => $orderDetail, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Update the specified OrderDetail in storage.
     *
     * @param  int              $id
     * @param UpdateOrderDetailRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOrderDetailRequest $request)
    {
        $orderDetail = $this->orderDetailRepository->findWithoutFail($id);

        if (empty($orderDetail)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.order-details.index'));
        }

        $orderDetail = $this->orderDetailRepository->updateRecord($request, $orderDetail);

        Flash::success($this->BreadCrumbName . ' updated successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.order-details.create'));
        } else {
            $redirect_to = redirect(route('admin.order-details.index'));
        }
        return $redirect_to->with(['title' => $this->BreadCrumbName]);
    }

    /**
     * Remove the specified OrderDetail from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $orderDetail = $this->orderDetailRepository->findWithoutFail($id);

        if (empty($orderDetail)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.order-details.index'));
        }

        $this->orderDetailRepository->deleteRecord($id);

        Flash::success($this->BreadCrumbName . ' deleted successfully.');
        return redirect(route('admin.order-details.index'))->with(['title' => $this->BreadCrumbName]);
    }
}

resources/views/admin/order_details/create.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.order-details.store', 'files' => true]) !!}

                        @include('admin.order_details.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/order_details/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.order-details.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @ability('super-admin' ,'order-details.show')
    <a href="{{ route('admin.order-details.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @endability
    @ability('super-admin' ,'order-details.edit')
    <a href="{{ route('admin.order-details.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endability
    @ability('super-admin' ,'order-details.destroy')
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
    ]) !!}
    @endability
</div>
{!! Form::close() !!}

resources/views/admin/order_details/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $orderDetail->name }} <small>{{ $title }}</small>
@endsection

@section('content')
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($orderDetail, ['route' => ['admin.order-details.update', $orderDetail->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('admin.order_details.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/order_details/fields.blade.php
<!-- Order Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('order_id', 'Order Id:') !!}
    {!! Form::text('order_id', null, ['class' => 'form-control', 'placeholder'=>'Enter order_id']) !!}
</div>

<!-- No Bags Field -->
<div class="form-group col-sm-6">
    {!! Form::label('no_bags', 'No Bags:') !!}
    {!! Form::text('no_bags', null, ['class' => 'form-control', 'placeholder'=>'Enter no_bags']) !!}
</div>

<!-- Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('type', 'Type:') !!}
    {!! Form::text('type', null, ['class' => 'form-control', 'placeholder'=>'Enter type']) !!}
</div>

<!-- Detergent Field -->
<div class="form-group col-sm-6">
    {!! Form::label('detergent', 'Detergent:') !!}
    {!! Form::text('detergent', null, ['class' => 'form-control', 'placeholder'=>'Enter detergent']) !!}
</div>

<!-- Folded Field -->
<div class="form-group col-sm-6">
    {!! Form::label('folded', 'Folded:') !!}
    {!! Form::text('folded', null, ['class' => 'form-control', 'placeholder'=>'Enter folded']) !!}
</div>

<!-- Hung Field -->
<div class="form-group col-sm-6">
    {!! Form::label('hung', 'Hung:') !!}
    {!! Form::text('hung', null, ['class' => 'form-control', 'placeholder'=>'Enter hung']) !!}
</div>

<!-- Instruction Field -->
<div class="form-group col-sm-6">
    {!! Form::label('instruction', 'Instruction:') !!}
    {!! Form::text('instruction', null, ['class' => 'form-control', 'placeholder'=>'Enter instruction']) !!}
</div>

<!-- Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price', 'Price:') !!}
    {!! Form::text('price', null, ['class' => 'form-control', 'placeholder'=>'Enter price']) !!}
</div>

<!-- Donation Field -->
<div class="form-group col-sm-6">
    {!! Form::label('donation', 'Donation:') !!}
    {!! Form::text('donation', null, ['class' => 'form-control', 'placeholder'=>'Enter donation']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    @if(!isset($orderDetail))
        {!! Form::submit(__('Save And Add Translations'), ['class' => 'btn btn-primary', 'name'=>'translation']) !!}
    @endif
    {!! Form::submit(__('Save And Add More'), ['class' => 'btn btn-primary', 'name'=>'continue']) !!}
    <a href="{!! route('admin.order-details.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/order_details/index.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.order_details.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/order_details/show.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <dl class="dl-horizontal">
                        @include('admin.order_details.show_fields')
                    </dl>
                    {!! Form::open(['route' => ['admin.order-details.destroy', $orderDetail->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @ability('super-admin' ,'order-details.show')
                        <a href="{!! route('admin.order-details.index') !!}" class="btn btn-default">
                            <i class="glyphicon glyphicon-arrow-left"></i> Back
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'order-details.edit')
                        <a href="{{ route('admin.order-details.edit', $orderDetail->id) }}" class='btn btn-default'>
                            <i class="glyphicon glyphicon-edit"></i> Edit
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'order-details.destroy')
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger',
                            'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
                        ]) !!}
                        @endability
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/order_details/show_fields.blade.php
<!-- Id Field -->
<dt>{!! Form::label('id', 'Id:') !!}</dt>
<dd>{!! $orderDetail->id !!}</dd>

<!-- Order Id Field -->
<dt>{!! Form::label('order_id', 'Order Id:') !!}</dt>
<dd>{!! $orderDetail->order_id !!}</dd>

<!-- No Bags Field -->
<dt>{!! Form::label('no_bags', 'No Bags:') !!}</dt>
<dd>{!! $orderDetail->no_bags !!}</dd>

<!-- Type Field -->
<dt>{!! Form::label('type', 'Type:') !!}</dt>
<dd>{!! $orderDetail->type !!}</dd>

<!-- Detergent Field -->
<dt>{!! Form::label('detergent', 'Detergent:') !!}</dt>
<dd>{!! $orderDetail->detergent !!}</dd>

<!-- Folded Field -->
<dt>{!! Form::label('folded', 'Folded:') !!}</dt>
<dd>{!! $orderDetail->folded !!}</dd>

<!-- Hung Field -->
<dt>{!! Form::label('hung', 'Hung:') !!}</dt>
<dd>{!! $orderDetail->hung !!}</dd>

<!-- Instruction Field -->
<dt>{!! Form::label('instruction', 'Instruction:') !!}</dt>
<dd>{!! $orderDetail->instruction !!}</dd>

<!-- Price Field -->
<dt>{!! Form::label('price', 'Price:') !!}</dt>
<dd>{!! $orderDetail->price !!}</dd>

<!-- Donation Field -->
<dt>{!! Form::label('donation', 'Donation:') !!}</dt>
<dd>{!! $orderDetail->donation !!}</dd>

<!-- Created At Field -->
<dt>{!! Form::label('created_at', 'Created At:') !!}</dt>
<dd>{!! $orderDetail->created_at !!}</dd>

<!-- Updated At Field -->
<dt>{!! Form::label('updated_at', 'Updated At:') !!}</dt>
<dd>{!! $orderDetail->updated_at !!}</dd>

<!-- Deleted At Field -->
<dt>{!! Form::label('deleted_at', 'Deleted At:') !!}</dt>
<dd>{!! $orderDetail->deleted_at !!}</dd>

resources/views/admin/order_details/table.blade.php
@push('css')
    @include('admin.layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush