routes/admin.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');


Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');

//Menu #TODO need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::post('updateChannelPosition', 'MenuController@update_channel_position')->name('channels');

Route::resource('settings', 'SettingController');

Route::resource('order-details', 'OrderDetailController');

//added this
Route::post('/universities/toggleBtn', 'UniversityController@toggleBtn');

Route::post('/customers/toggleBtn', 'CustomerController@toggleBtn');

Route::post('/jobs/toggleBtn', 'JobController@toggleBtn');

Route::post('/transactions/toggleBtn', 'TransactionController@toggleBtn');

Route::post('/refund-customers/refund', 'RefundCustomerController@refund');

Route::post('/refund-customers/toggleBtn', 'RefundCustomerController@toggleBtn');

Route::resource('customers', 'CustomerController');

Route::resource('washers', 'WasherController');

Route::resource('universities', 'UniversityController');

Route::resource('transactions', 'TransactionController');

Route::resource('orders', 'OrderController');

Route::resource('transactions', 'TransactionController');

Route::resource('universities', 'UniversityController');

Route::resource('reports', 'ReportController');

Route::resource('jobs', 'JobController');

Route::resource('total-scholarships', 'TotalScholarshipController');

Route::resource('refund-customers', 'RefundCustomerController');

Route::resource('cancelled-orders', 'CancelledOrderController');

Route::resource('cancelled-orders', 'CancelledOrderController');

Route::resource('cancelled-orders', 'CancelledOrderController');

Route::resource('wallets', 'WalletController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/RefundCustomer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property integer id
 * @property string name
 * @property string created_at
 * @property string updated_at
 * @property string deleted_at
 *
 * @SWG\Definition(
 *      definition="RefundCustomer",
 *      required={"user_id", "university_id", "amount", "status"},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="user_id",
 *          description="user_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="university_id",
 *          description="university_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="amount",
 *          description="amount",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="status",
 *          description="status",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class RefundCustomer extends Model
{
    use SoftDeletes;

    public $table = 'refund_customers';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'user_id',
        'university_id',
        'amount',
        'status'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'user_id' => 'integer',
        'university_id' => 'integer',
        'amount' => 'integer',
        'status' => 'boolean'
    ];

    /**
     * The objects that should be append to toArray.
     *
     * @var array
     */
     protected $with = [];

    /**
     * The attributes that should be append to toArray.
     *
     * @var array
     */
    protected $appends = [];

    /**
     * The attributes that should be visible in toArray.
     *
     * @var array
     */
    protected $visible = [];

    /**
     * Validation create rules
     *
     * @var array
     */
    public static $rules = [
        'user_id' => 'required',
        'university_id' => 'required',
        'amount' => 'required',
        'status' => 'required'
    ];

    /**
     * Validation update rules
     *
     * @var array
     */
    public static $update_rules = [
        'user_id' => 'required',
        'university_id' => 'required',
        'amount' => 'required',
        'status' => 'required'
    ];

    /**
     * Validation api rules
     *
     * @var array
     */
    public static $api_rules = [
        'user_id' => 'required',
        'university_id' => 'required',
        'amount' => 'required',
        'status' => 'required'
    ];
	
	/**
     * Validation api update rules
     *
     * @var array
     */
    public static $api_update_rules = [
        'user_id' => 'required',
        'university_id' => 'required',
        'amount' => 'required',
        'status' => 'required'
    ];

    public function user(){
       return $this->belongsTo(User::class);
    }

    public function university(){
        return $this->belongsTo(University::class);
    }
}

app/Http/Controllers/Admin/RefundCustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\BreadcrumbsRegister;
use App\DataTables\Admin\RefundCustomerDataTable;
use App\Http\Requests\Admin\CreateRefundCustomerRequest;
use App\Http\Requests\Admin\UpdateRefundCustomerRequest;
use App\Models\RefundCustomer;
use App\Repositories\Admin\RefundCustomerRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Laracasts\Flash\Flash;
use Illuminate\Http\Response;

use PayPal\Api\Amount;
use PayPal\Api\Refund;
use PayPal\Api\RefundRequest;
use PayPal\Api\Sale;
use PayPal\Exception\PayPalConnectionException;

class RefundCustomerController extends AppBaseController
{
    /** ModelName */
    private $ModelName;

    /** BreadCrumbName */
    private $BreadCrumbName;

    /** @var  RefundCustomerRepository */
    private $refundCustomerRepository;

    public function __construct(RefundCustomerRepository $refundCustomerRepo)
    {
        $this->refundCustomerRepository = $refundCustomerRepo;
        $this->ModelName = 'refund-customers';
        $this->BreadCrumbName = 'Refund Customers';
    }

    /**
     * Display a listing of the RefundCustomer.
     *
     * @param RefundCustomerDataTable $refundCustomerDataTable
     * @return Response
     */
    public function index(RefundCustomerDataTable $refundCustomerDataTable)
    {
        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName);
        return $refundCustomerDataTable->render('admin.refund_customers.index', ['title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for creating a new RefundCustomer.
     *
     * @return Response
     */
    public function create()
    {
        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName);
        return view('admin.refund_customers.create')->with(['title' => $this->BreadCrumbName]);
    }

    /**
     * Store a newly created RefundCustomer in storage.
     *
     * @param CreateRefundCustomerRequest $request
     *
     * @return Response
     */
    public function store(CreateRefundCustomerRequest $request)
    {
        $refundCustomer = $this->refundCustomerRepository->saveRecord($request);

        Flash::success($this->BreadCrumbName . ' saved successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.refund-customers.create'));
        } elseif (isset($request->translation)) {
            $redirect_to = redirect(route('admin.refund-customers.edit', $refundCustomer->id));
        } else {
            $redirect_to = redirect(route('admin.refund-customers.index'));
        }
        return $redirect_to->with([
            'title' => $this->BreadCrumbName
        ]);
    }

    /**
     * Display the specified RefundCustomer.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $refundCustomer = $this->refundCustomerRepository->findWithoutFail($id);

        if (empty($refundCustomer)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.refund-customers.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName, $refundCustomer);
        return view('admin.refund_customers.show')->with(['refundCustomer' => $refundCustomer, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for editing the specified RefundCustomer.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $refundCustomer = $this->refundCustomerRepository->findWithoutFail($id);

        if (empty($refundCustomer)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.refund-customers.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName, $this->BreadCrumbName, $refundCustomer);
        return view('admin.refund_customers.edit')->with(['refundCustomer' => $refundCustomer, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Update the specified RefundCustomer in storage.
     *
     * @param  int $id
     * @param UpdateRefundCustomerRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRefundCustomerRequest $request)
    {
        $refundCustomer = $this->refundCustomerRepository->findWithoutFail($id);

        if (empty($refundCustomer)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.refund-customers.index'));
        }

        $refundCustomer = $this->refundCustomerRepository->updateRecord($request, $refundCustomer);

        Flash::success($this->BreadCrumbName . ' updated successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.refund-customers.create'));
        } else {
            $redirect_to = redirect(route('admin.refund-customers.index'));
        }
        return $redirect_to->with(['title' => $this->BreadCrumbName]);
    }

    /**
     * Remove the specified RefundCustomer from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $refundCustomer = $this->refundCustomerRepository->findWithoutFail($id);

        if (empty($refundCustomer)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.refund-customers.index'));
        }

        $this->refundCustomerRepository->deleteRecord($id);

        Flash::success($this->BreadCrumbName . ' deleted successfully.');
        return redirect(route('admin.refund-customers.index'))->with(['title' => $this->BreadCrumbName]);
    }

    public function toggleBtn(Request $request)
    {
        if ($request->id) {
            $refund = $this->refundCustomerRepository->find($request->id);
            if ($refund->status == 1) {
                $input['status'] = 0;
                Flash::success('University Activated successfully.');
            } else {
                $input['status'] = 1;
                Flash::success('University Blocked successfully.');
            }

            RefundCustomer::where('id', $refund->id)->update($input);
            return redirect()->back();
        }
    }

    public function refund(Request $request)
    {
//        dd($request);
        $amt = new Amount();
        //$amt = $request->get('amount');

        $amt->setTotal(19.98)
            ->setCurrency('USD');

        $refund = new RefundRequest();
        $refund->setAmount($amt);

//        $sale = new Sale();
//        $sale->setId("PAYID-LXP6YQQ4DS316267D8405024");
        //psyment ID mentioned above
//        $sale->setId($saleId);
        try {
            $apiContext =
                new \PayPal\Rest\ApiContext(
                    new \PayPal\Auth\OAuthTokenCredential(
                        env('PAYPAL_CLIENT_ID', ''),
                        env('PAYPAL_SECRET', '')
                    )
                );
//            $refundedSale = $sale->refundSale($refund, $apiContext);
        }catch (PayPalConnectionException $e) {
            echo $e->getData(); // This will print a JSON which has specific details about the error.
            exit;
        }

        return 'Successful';
    }
}

resources/views/admin/refund_customers/create.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.refund-customers.store', 'files' => true]) !!}

                        @include('admin.refund_customers.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/refund_customers/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.refund-customers.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @ability('super-admin' ,'refund-customers.show')
    <a href="{{ route('admin.refund-customers.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @endability
    @ability('super-admin' ,'refund-customers.edit')
    <a href="{{ route('admin.refund-customers.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endability
    @ability('super-admin' ,'refund-customers.destroy')
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
    ]) !!}
    @endability
</div>
{!! Form::close() !!}

resources/views/admin/refund_customers/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $refundCustomer->name }} <small>{{ $title }}</small>
@endsection

@section('content')
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($refundCustomer, ['route' => ['admin.refund-customers.update', $refundCustomer->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('admin.refund_customers.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/refund_customers/fields.blade.php
<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::text('user_id', null, ['class' => 'form-control', 'placeholder'=>'Enter user_id']) !!}
</div>

<!-- University Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('university_id', 'University Id:') !!}
    {!! Form::text('university_id', null, ['class' => 'form-control', 'placeholder'=>'Enter university_id']) !!}
</div>

<!-- Amount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('amount', 'Amount:') !!}
    {!! Form::text('amount', null, ['class' => 'form-control', 'placeholder'=>'Enter amount']) !!}
</div>

<!-- Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::text('status', null, ['class' => 'form-control', 'placeholder'=>'Enter status']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    @if(!isset($refundCustomer))
        {!! Form::submit(__('Save And Add Translations'), ['class' => 'btn btn-primary', 'name'=>'translation']) !!}
    @endif
    {!! Form::submit(__('Save And Add More'), ['class' => 'btn btn-primary', 'name'=>'continue']) !!}
    <a href="{!! route('admin.refund-customers.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/refund_customers/index.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.refund_customers.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/refund_customers/show.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <dl class="dl-horizontal">
                        @include('admin.refund_customers.show_fields')
                    </dl>
                    {!! Form::open(['route' => ['admin.refund-customers.destroy', $refundCustomer->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @ability('super-admin' ,'refund-customers.show')
                        <a href="{!! route('admin.refund-customers.index') !!}" class="btn btn-default">
                            <i class="glyphicon glyphicon-arrow-left"></i> Back
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'refund-customers.edit')
                        <a href="{{ route('admin.refund-customers.edit', $refundCustomer->id) }}" class='btn btn-default'>
                            <i class="glyphicon glyphicon-edit"></i> Edit
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'refund-customers.destroy')
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger',
                            'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
                        ]) !!}
                        @endability
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/refund_customers/show_fields.blade.php
<!-- Id Field -->
{{--<dt>{!! Form::label('id', 'Id:') !!}</dt>--}}
{{--<dd>{!! $refundCustomer->id !!}</dd>--}}

<!-- User Id Field -->
<dt>{!! Form::label('user_id', 'Customer Name:') !!}</dt>
<dd>{!! $refundCustomer->user->name !!}</dd>

<!-- University Id Field -->
<dt>{!! Form::label('university_id', 'University:') !!}</dt>
<dd>{!! $refundCustomer->university->name !!}</dd>

<!-- Amount Field -->
<dt>{!! Form::label('amount', 'Amount:') !!}</dt>
<dd>{!! '$' . $refundCustomer->amount !!}</dd>

<!-- Status Field -->
<dt>{!! Form::label('status', 'Status:') !!}</dt>

@if($refundCustomer->status == 0)
<dd>{!! 'Refunded' !!}</dd>
@else
    <dd>{!! 'Pending' !!}</dd>
    @endif

<!-- Created At Field -->
<dt>{!! Form::label('created_at', 'Created At:') !!}</dt>
<dd>{!! $refundCustomer->created_at !!}</dd>

<!-- Updated At Field -->
<dt>{!! Form::label('updated_at', 'Updated At:') !!}</dt>
<dd>{!! $refundCustomer->updated_at !!}</dd>

<!-- Deleted At Field -->
{{--<dt>{!! Form::label('deleted_at', 'Deleted At:') !!}</dt>--}}
{{--<dd>{!! $refundCustomer->deleted_at !!}</dd>--}}

resources/views/admin/refund_customers/table.blade.php
@push('css')
    @include('admin.layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush